### ISSUE TITLE
No Bridges found 

### ISSUE THREAD

**Issue by nimahkh** [lihbr/nuxt-hue#1]
## Version

Node: 12.0.0 
Nuxt: 1.0.0 

Hey guys, I was going to start the `nuxt-hue` as it is mentioned in document by following command   : 
```bash
~/.yarn/bin/nuxt-hue setup
```

But I faced with this error:

```bash
✖ Discovering Bridges...
  → No Bridges Found
  Pairing...
  Saving Bridge...

 ERROR  No Bridges Found, try again:           nuxt-hue 10:06:54

  $ nuxt-hue connect

```

Also I tried the `connect` command, but same error faced. as I understand, there is a code that is trying to connect to a URL with this pattern : 
```js
get api(): string {
    return `http://${this.ip}/api`;
  }
```
I am not sure is it the problem or no. 

Any idea?

**Comment by lihbr** [comment]
Hey @nimahkh thanks for opening an issue!

Just to be sure: do you have Philips Hue with a bridge running on your wifi? Basically the setup/connect commands try to have a handshake with it.

**Comment by lihbr** [comment]
Closing the issue for now, feel free to reopen if you want to continue the troubleshooting process 👌
